pipeline {
    node('maven')
    stages {
      stage('Static Analysis') {
      container('maven'){
      steps{
      withSonarQubeEnv('sonar') 
      {
        sh 'mvn clean package sonar:sonar'
   	    echo 'Static Analysis Completed'
      }
      }
    }
}
    }
}